name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install paket and other project tools
      run: dotnet tool restore
    - name: Install dependencies
      run: dotnet paket install
    - name: Test
      run: dotnet test Tests/Tests.fsproj --no-restore --verbosity normal
